### ISSUE TITLE
Test failing - error with instanceof

### ISSUE THREAD

**Issue by cameronjacoby** [sf-wdi-24/apartment-oop#1]
In the solution branch, this test fails: https://github.com/sf-wdi-24/apartment-oop/blob/3ceaffee880eaccf8af3d397bd4b45779a3ab23a/test/people/managerTest.js#L13

Error message: TypeError: Expecting a function in instanceof check, but got #<Apartment>

From what I can figure out, `Apartment` equals `{}` inside the `addApartment` function here: https://github.com/sf-wdi-24/apartment-oop/blob/3ceaffee880eaccf8af3d397bd4b45779a3ab23a/src/people/manager.js#L14

I don't know why this is happening, but my best guess is it's because `Apartment` is required in `manager.js` and `Manager` is required in `apartment.js`.

I want the students to do an `instanceof` check before adding an apartment to a manager's apartments.

@eerwitt Would you mind taking a look at this? I'm out of ideas. Definitely can't have one of the specs failing in the solution branch :disappointed:

**Comment by eerwitt** [comment]
@cameronjacoby sure no prob, you were on the right track. This is a common issue (across languages) called circular dependencies. In order to work around it, I used a solution which is recommended here: https://coderwall.com/p/myzvmg/circular-dependencies-in-node-js

In practice it is good to avoid circular dependencies but I think it makes things clear for this challenge.

**Comment by cameronjacoby** [comment]
@eerwitt Thank you so much! I knew I was close, but wasn't googling the right thing. :grimacing:
